"""
Training Configuration and Gymnasium Script Exporter.
Exports complete machine-readable environment, scenario, and experiment bundles:
- environment.json
- scenario.json
- experiment.json
- run_gym_training.py (Standalone executable Gymnasium training runner)
"""

from __future__ import annotations
import json
import os
from typing import Dict, Any, Optional

from sim_env.experiment import ExperimentConfig
from sim_env.scenario_designer import ScenarioDefinition


class TrainingExporter:
    """
    Exports declarative environments and experiments into standard formats
    for consumption by external RL frameworks (Stable-Baselines3, CleanRL, Ray, PyTorch).
    """
    @classmethod
    def export_training_bundle(
        cls,
        output_dir: str,
        env_project: Any,  # EnvironmentProject
        scenario: Optional[ScenarioDefinition] = None,
        experiment: Optional[ExperimentConfig] = None
    ) -> Dict[str, str]:
        """
        Exports environment.json, scenario.json, experiment.json, and run_gym_training.py.
        Returns dict of file paths generated.
        """
        os.makedirs(output_dir, exist_ok=True)
        scenario = scenario or ScenarioDefinition.get_standard_scenarios().get("basic_lane_following")
        experiment = experiment or ExperimentConfig(
            environment_name=env_project.name,
            scenario_id=scenario.scenario_id if scenario else "default"
        )

        env_path = os.path.join(output_dir, "environment.json")
        scen_path = os.path.join(output_dir, "scenario.json")
        exp_path = os.path.join(output_dir, "experiment.json")
        runner_path = os.path.join(output_dir, "run_gym_training.py")

        # 1. environment.json
        with open(env_path, "w", encoding="utf-8") as f:
            json.dump(env_project.to_dict(), f, indent=2)

        # 2. scenario.json
        with open(scen_path, "w", encoding="utf-8") as f:
            json.dump(scenario.to_dict(), f, indent=2)

        # 3. experiment.json
        with open(exp_path, "w", encoding="utf-8") as f:
            json.dump(experiment.to_dict(), f, indent=2)

        # 4. run_gym_training.py
        runner_code = cls._generate_gym_runner_script(
            env_file="environment.json",
            scenario_file="scenario.json",
            experiment_file="experiment.json"
        )
        with open(runner_path, "w", encoding="utf-8") as f:
            f.write(runner_code)

        return {
            "environment": env_path,
            "scenario": scen_path,
            "experiment": exp_path,
            "runner": runner_path
        }

    @staticmethod
    def _generate_gym_runner_script(env_file: str, scenario_file: str, experiment_file: str) -> str:
        return f'''"""
Auto-generated Gymnasium Training Runner.
Generated by AI Environment Simulation Studio (Phase 3).
"""

import sys
import os
import json
import numpy as np

# Ensure project root is in python path
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from sim_project.serializer import EnvironmentProject
from sim_env.environment import SimulationEnvironment
from sim_env.scenario_designer import ScenarioDefinition
from sim_env.experiment import ExperimentConfig
from sim_client.agents.ppo_baseline import PPORunner


def main():
    dir_path = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Load Configurations
    with open(os.path.join(dir_path, "{env_file}"), "r", encoding="utf-8") as f:
        proj_data = json.load(f)
    project = EnvironmentProject.from_dict(proj_data)

    with open(os.path.join(dir_path, "{scenario_file}"), "r", encoding="utf-8") as f:
        scen_data = json.load(f)
    scenario = ScenarioDefinition.from_dict(scen_data)

    with open(os.path.join(dir_path, "{experiment_file}"), "r", encoding="utf-8") as f:
        exp_data = json.load(f)
    experiment = ExperimentConfig.from_dict(exp_data)

    print(f"=== Starting RL Experiment: {{experiment.name}} ===")
    print(f"Environment: {{project.name}}")
    print(f"Scenario:    {{scenario.name}}")
    print(f"Algorithm:   {{experiment.algorithm}}")
    print(f"Total Steps: {{experiment.total_timesteps}}")

    # 2. Instantiate Simulator Environment
    env = SimulationEnvironment(
        road_def=project.road_def,
        vehicle_config=project.vehicle_config,
        action_config=project.action_config,
        observation_schema=project.observation_schema,
        reward_config=project.reward_config,
        termination_config=project.termination_config,
        randomization_config=project.randomization_config,
        scenario_config=project.scenario_config,
        agent=project.agent,
        episode_config=project.episode_config,
        scenario_def=scenario,
        seed=experiment.seed
    )
    if project.entities:
        for ent in project.entities:
            env.add_entity(ent)

    # 3. Launch PPO Runner
    runner = PPORunner(
        env=env,
        lr=experiment.learning_rate,
        gamma=experiment.gamma,
        gae_lambda=experiment.gae_lambda,
        clip_coef=experiment.clip_coef,
        batch_size=experiment.batch_size,
        num_epochs=experiment.num_epochs,
        num_steps=experiment.rollout_steps,
        seed=experiment.seed
    )

    print("\\nExecuting training rollouts...")
    metrics = runner.train(total_timesteps=experiment.total_timesteps)
    print("\\n=== Training Finished Successfully ===")
    print(f"Episodes Completed: {{metrics.get('episodes_completed', 0)}}")
    if metrics.get('episode_returns'):
        print(f"Final 5 Return Mean: {{np.mean(metrics['episode_returns'][-5:]):.2f}}")


if __name__ == "__main__":
    main()
'''
